image:
  repository: payment-history-svc-api

containerPort: 5005

env:
  SERVER_PORT: 5005
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  LOGGING_STRUCTURED_FORMAT_CONSOLE: ecs
  JAVA_OPTS: -Xmx256m
  OTLP_TRACING_ENDPOINT: http://tempo.observability:4318/v1/traces

datasource:
  enabled: true
  host: bank-postgres-rw
  database: payment_history_db
  credentialsSecret: payment-history-service-db-credentials

messaging:
  enabled: true
  consumes:
    payment-snapshot-events: payment-snapshot-events

migration:
  enabled: true
  image:
    repository: payment-history-svc-db-migration-app
