package org.banksolution.enums;

public enum PaymentStatus {
    INITIATED,
    AUTHORISATION_PENDING,
    AUTHORISED,
    AUTHORISATION_DECLINED,
    FRAUD_CHECK_PENDING,
    FRAUD_CHECK_APPROVED,
    FRAUD_CHECK_FAILED,
    MANUAL_REVIEW_REQUIRED,
    SETTLEMENT_PENDING,
    SETTLED,
    RELEASE_PENDING,
    RELEASED,
    COMPLETED,
    BLOCKED,
    FAILED,
    OVERRIDE_APPROVED,
    OVERRIDE_REJECTED
}
