package org.banksolution.enums;

public enum PaymentStatus {
    INITIATED,
    FRAUD_CHECK_PENDING,
    FRAUD_CHECK_APPROVED,
    FRAUD_CHECK_FAILED,
    MANUAL_REVIEW_REQUIRED,
    ACCOUNT_CHARGE_PENDING,
    ACCOUNT_CHARGED,
    COMPLETED,
    BLOCKED,
    FAILED
}
