
# Database local config
spring.datasource.url=${DB_SERVICE_URL:jdbc:postgresql://localhost:5433/payment_history_db}
spring.datasource.username=${DB_SERVICE_USERNAME:default}
spring.datasource.password=${DB_SERVICE_PASSWORD:default}
