serviceType: gateway

image:
  repository: backoffice-gateway-svc

containerPort: 3030

env:
  SERVER_PORT: 3030
  CORS_ORIGINS: http://localhost:6060
  CUSTOMER_SERVICE_URL: http://customer-service:5001
  ACCOUNT_SERVICE_URL: http://account-service:5002
  PAYMENT_SERVICE_URL: http://payment-service:5003
  PAYMENT_ENGINE_SERVICE_URL: http://payment-engine-service:5004
  PAYMENT_HISTORY_SERVICE_URL: http://payment-history-service:5005
  RISK_ENGINE_SERVICE_URL: http://risk-engine-service:5006
  NETWORK_TOPOLOGY_SERVICE_URL: http://network-topology-service:5007
  CUSTOMER_PROFILE_SERVICE_URL: http://customer-profile-service:5008
  CONFIGURATION_SERVICE_URL: http://configuration-service:5009
  LEDGER_SERVICE_URL: http://ledger-service:5013
  BENEFICIARY_SERVICE_URL: http://beneficiary-service:5014
  MARL_ORCHESTRATOR_URL: http://marl-orchestrator.ai:1004

networkPolicy:
  egress:
    - customer-service
    - account-service
    - payment-service
    - payment-engine-service
    - payment-history-service
    - risk-engine-service
    - network-topology-service
    - customer-profile-service
    - configuration-service
    - ledger-service
    - beneficiary-service
    - ai/marl-orchestrator
