image:
  repository: configuration-svc-api

containerPort: 5009

env:
  SERVER_PORT: 5009
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate

datasource:
  enabled: true
  database: configuration_service_db
  credentialsSecret: configuration-service-db-credentials

migration:
  enabled: true
  image:
    repository: configuration-svc-db-migration-app
