serviceType: java-microservice

image:
  repository: risk-engine-svc-api

containerPort: 5006

env:
  SERVER_PORT: 5006
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  ACCOUNT_SERVICE_URL: http://account-service:5002/api/v1/accounts
  NETWORK_TOPOLOGY_SERVICE_URL: http://network-topology-service:5007/api/v1/networks
  CUSTOMER_PROFILE_SERVICE_URL: http://customer-profile-service:5008/api/v1/customer-profiles

datasource:
  enabled: true
  database: risk_engine_db
  credentialsSecret: risk-engine-service-db-credentials

messaging:
  enabled: true
  consumerGroup: risk-engine-group
  consumes:
    risk-assessment-requested: risk.assessment.requested
    fraud-analysis-completed: fraud.analysis.completed
  produces:
    risk-assessment-completed: risk.assessment.completed
    fraud-analysis-requested: fraud.analysis.requested

migration:
  enabled: true
  image:
    repository: risk-svc-db-migration-app

networkPolicy:
  ingress:
    - backoffice-gateway
  egress:
    - account-service
    - network-topology-service
    - customer-profile-service
