clusterName: bank-postgres
instances: 1
imageName: ghcr.io/cloudnative-pg/postgresql:16

storage:
  size: 5Gi

parameters:
  max_connections: "200"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

createCredentialsSecrets: false
credentials: { }

databases:
  - service: configuration-service
    database: configuration_service_db
    role: configuration_service
  - service: risk-engine-service
    database: risk_engine_db
    role: risk_engine
  - service: account-service
    database: account_service_db
    role: account_service
  - service: customer-service
    database: customer_service_db
    role: customer_service
  - service: customer-profile-service
    database: customer_profile_db
    role: customer_profile
  - service: payment-history-service
    database: payment_history_db
    role: payment_history
  - service: payment-service
    database: payment_service_db
    role: payment_service
  - service: payment-engine-service
    database: payment_engine_db
    role: payment_engine
