clusterName: bank-postgres
instances: 1
imageName: ghcr.io/cloudnative-pg/postgresql:16

storage:
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

createCredentialsSecrets: false
credentials: { }

databases:
  - service: configuration-service
    database: configuration_service_db
    role: configuration_service
  - service: risk-engine-service
    database: risk_engine_db
    role: risk_engine
