spring.application.name=risk-engine-svc
server.port=5006

# Database config
spring.datasource.url=${DB_SERVICE_URL:jdbc:postgresql://localhost:5433/risk_engine_db}
spring.datasource.username=${DB_SERVICE_USERNAME:default}
spring.datasource.password=${DB_SERVICE_PASSWORD:default}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.schema-registry.url=${SCHEMA_REGISTRY_URL:http://localhost:8081}
spring.kafka.consumer.group-id=risk-engine-group

# Kafka Topics
# Incoming events
spring.kafka.topics.incoming.risk-assessment-requested=risk.assessment.requested
spring.kafka.topics.incoming.fraud-analysis-completed=fraud.analysis.completed

# Outgoing events
spring.kafka.topics.outgoing.risk-assessment-completed=risk.assessment.completed
spring.kafka.topics.outgoing.fraud-analysis-requested=fraud.analysis.requested

# OpenFeign configuration
spring.cloud.openfeign.client.config.default.loggerLevel=BASIC
spring.cloud.openfeign.client.config.default.readTimeout=5000
spring.cloud.openfeign.client.config.default.connectTimeout=5000

integration.account-service.url=${ACCOUNT_SERVICE_URL:http://localhost:5002/api/v1/accounts}

# Actuator endpoints
springdoc.show-actuator=true
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=ALWAYS
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# Server configuration for containerized environments
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
