{{- if .Values.createCredentialsSecrets }}
{{- range .Values.databases }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .service }}-db-credentials
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: {{ .role | quote }}
  password: {{ required (printf "credentials.%s is required when createCredentialsSecrets is true" .service) (get $.Values.credentials .service) | quote }}
{{- end }}
{{- end }}
