server.port=5003
spring.application.name=payment-svc

# Swagger/OpenAPI configuration
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.show-actuator=true

# Database config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/payment_service_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:default}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:default}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=ALWAYS
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# Server configuration
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

# Kafka configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.schema-registry.url=${SCHEMA_REGISTRY_URL:http://localhost:8081}

# Kafka Topics
spring.kafka.topics.outgoing.payment-created=payment-created-events

integration.account-service.url=${ACCOUNT_SERVICE_URL:http://localhost:5002/api/v1/accounts}

