apiVersion: v2
name: risk-engine-service
description: Extracts risk features, requests MARL fraud analysis and returns the risk assessment to payment-engine
type: application
version: 0.1.0
appVersion: 0.0.1-SNAPSHOT
dependencies:
  - name: banksolution-common
    version: 0.1.0
    repository: file://../../library/banksolution-common
