apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: {{ .Values.clusterName }}
spec:
  kafka:
    version: {{ .Values.version }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
        networkPolicyPeers:
          - namespaceSelector: { }
            podSelector:
              matchLabels:
                banksolution.io/kafka-client: "true"
          - podSelector:
              matchLabels:
                strimzi.io/cluster: {{ .Values.clusterName }}
    authorization:
      type: simple
      superUsers:
        {{- toYaml .Values.superUsers | nindent 8 }}
    config:
      {{- toYaml .Values.config | nindent 6 }}
  entityOperator:
    topicOperator:
      jvmOptions:
        {{- toYaml .Values.topicOperator.jvmOptions | nindent 8 }}
      resources:
        {{- toYaml .Values.topicOperator.resources | nindent 8 }}
    userOperator:
      jvmOptions:
        {{- toYaml .Values.userOperator.jvmOptions | nindent 8 }}
      resources:
        {{- toYaml .Values.userOperator.resources | nindent 8 }}
