plugins {
    id 'java-library'
}

group = 'org.bank.solution'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    api project(':scheduler-library:scheduler-db-migration-changelog')
    api project(':outbox-library:outbox-db-migration-changelog')
}

test {
    useJUnitPlatform()
}