apiVersion: v2
name: customer-service
description: Customer master data
type: application
version: 0.1.0
appVersion: 0.0.1-SNAPSHOT
dependencies:
  - name: banksolution-common
    version: 0.1.0
    repository: file://../../library/banksolution-common
